spring:
  application:
    name: ribbon-consumer
server:
  port: 3333

eureka:
  client:
    service-url:
      defaultZone: http://master:1111/eureka/,http://backup1:1112/eureka/,http://backup2:1113/eureka/
