spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 5555

#不依赖eureka组件，直接url方式实现路由功能
#zuul.routes.api-a-url.path=/api-a-url/**
#zuul.routes.api-a-url.url=http://localhost:2220/
#zuul.routes.api-b-url.path=/api-a-url/**
#zuul.routes.api-b-url.url=http://localhost:2221/

#依赖eureka组件，通过serviceId实现路由
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-add
#    api-b:
#      path: /api-b/**
#      serviceId: service-b
  sensitive-headers:  # blacklist，如果不过滤，则须显式设为空。

eureka:
  client:
    serviceUrl:
      defaultZone: http://master:1111/eureka/,http://backup1:1112/eureka/,http://backup2:1113/eureka/
