spring:
  application:
    name: config-server
  cloud:
    config:
      server:
          git:
              uri: https://github.com/wu05281/springcloud
              searchPaths: file-config
              username: wu05281
server:
  port: 7001