spring:
  application:
    name: feign-consumer
server:
  port: 3333


eureka:
  client:
    service-url:
      defaultZone: http://master:1111/eureka/,http://backup1:1112/eureka/,http://backup2:1113/eureka/

#这个必须加，但是代码提示没有这个配置，太坑爹了
feign:
  hystrix:
    enabled: true
